# Generated by Django 5.0 on 2024-06-21 14:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_user_tracked_product"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="tracked_product",
        ),
    ]
