# Generated by Django 5.0 on 2024-05-31 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('consumptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='product',
            field=models.ManyToManyField(blank=True, related_name='users', to='consumptions.product'),
        ),
    ]
