# Generated by Django 5.0 on 2024-06-18 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='product',
            new_name='products',
        ),
    ]
