from django.urls import path
from .views import (
    ApiProductsList,
    ApiUnitsList,
    ApiMotivationsList,
    ApiTrackedProductsList,
    ApiAddConsumption,
    ApiConsumptionDetail,
    ApiConsumptionsListByTrackedProduct,
    ApiTrackingFrequenciesList,
    ApiDeleteTrackedProduct,
    ApiPauseTrackedProduct,
    ApiUnpauseTrackedProduct,
    ApiPausedTrackedProductsList,
)

urlpatterns = [
    path("products", ApiProductsList.as_view(), name="products"),
    path("products/<int:product_id>/units", ApiUnitsList.as_view(), name="units"),
    path(
        "products/<int:product_id>/motivations",
        ApiMotivationsList.as_view(),
        name="motivations",
    ),
    path(
        "tracked-products",
        ApiTrackedProductsList.as_view(),
        name="tracked-products",
    ),
    path(
        "tracked-products/paused",
        ApiPausedTrackedProductsList.as_view(),
        name="paused-tracked-products",
    ),
    path(
        "tracked-products/<int:tracked_product_id>",
        ApiDeleteTrackedProduct.as_view(),
        name="delete-tracked-product",
    ),
    path(
        "tracked-products/<int:tracked_product_id>/consumptions",
        ApiConsumptionsListByTrackedProduct.as_view(),
        name="consumptions-by-product",
    ),
    path(
        "tracked-products/<int:tracked_product_id>/consumptions/add-consumption",
        ApiAddConsumption.as_view(),
        name="add-consumption",
    ),
    path(
        "tracked-products/<int:tracked_product_id>/consumptions/<str:date>",
        ApiConsumptionDetail.as_view(),
        name="consumptions-by-date",
    ),
    path(
        "tracked-products/<int:tracked_product_id>/pause",
        ApiPauseTrackedProduct.as_view(),
        name="pause-tracked-product",
    ),
    path(
        "tracked-products/<int:tracked_product_id>/unpause",
        ApiUnpauseTrackedProduct.as_view(),
        name="unpause-tracked-product",
    ),
    path(
        "tracking-frequencies",
        ApiTrackingFrequenciesList.as_view(),
        name="tracking-frequencies",
    ),
]
