version: "3.8"
services:

  # db_dev:
  #   image: postgres:16.3
  #   restart: unless-stopped
  #   volumes:
  #     - db_dev:/var/lib/postgresql/data
  #   environment:
  #     POSTGRES_USER: ${DB_USER}
  #     POSTGRES_PASSWORD: ${DB_PASSWORD}
  #     POSTGRES_DB: ${DB_DEV_NAME}
  #   ports:
  #     - "${DB_DEV_PORT}:5433"  

  mailhog:
    image: mailhog/mailhog
    container_name: 'mailhog'
    ports:
      - "1025:1025"
      - "8025:8025"

  backend:
    restart: unless-stopped
    hostname: backend
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - "8002:8002"
    env_file: ./backend/.env
    volumes:
      - ./backend:/backend
    depends_on:
      - db_prod
      # - postgres_test
  db_prod:
    image: postgres:16.3
    restart: unless-stopped
    volumes:
      - db_prod:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: moinscestbien
    ports:
      - "5440:5432"

  frontend:
    restart: unless-stopped
    hostname: frontend
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - 5174:5173
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules

volumes:
  db_prod:
