# Generated by Django 5.0 on 2024-06-18 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumptions', '0006_products-motivations_populate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='motivation',
            new_name='motivations',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='unit',
            new_name='units',
        ),
    ]
