# Generated by Django 5.0 on 2024-06-21 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumptions', '0008_alter_consumption_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackedproduct',
            name='motivation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracked_products', to='consumptions.motivation'),
        ),
    ]
