# Generated by Django 5.0 on 2024-10-04 09:05

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("consumptions", "0009_trackingfrequency_alter_trackedproduct_start_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="trackedproduct",
            name="tracking_frequency",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tracked_products",
                to="consumptions.trackingfrequency",
            ),
        ),
        migrations.AlterField(
            model_name="trackedproduct",
            name="start_date",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
