# Generated by Django 5.0 on 2025-02-19 21:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("consumptions", "0010_trackedhabit_tracking_frequency_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="motivations",
            field=models.ManyToManyField(
                related_name="habits", to="consumptions.motivation"
            ),
        ),
    ]
