name: CI test

on:
  push:
    branches: 
      - "main"
  pull_request:
    branches: 
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: db_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready" --health-interval=10s --health-timeout=5s --health-retries=5

    env:
      DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
      DJANGO_SETTINGS_MODULE: moinscestbien.settings
      DB_NAME: db_test
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: localhost
      DB_DOCKER_PORT: "5432"
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/db_test

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Backend Dependencies
        working-directory: ./backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run migrations
        working-directory: ./backend
        run: |
          python manage.py migrate

      - name: Run Backend Tests
        working-directory: ./backend
        run: |
          python manage.py test

      - name : Lint Backend Code
        working-directory: ./backend
        run: black --check .

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install Frontend Dependencies
        working-directory: ./frontend
        run: npm install

      - name: Lint Frontend Code
        working-directory: ./frontend
        run: npm run lint

      - name: Build Frontend
        working-directory: ./frontend
        run: npm run build
